name: Laravel-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.4-beta

    steps:
    - uses: actions/checkout@v2
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan migrate
        php artisan serve
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit tests/
